POST http://localhost:8080/api/visitors
Content-Type: application/json

{
  "name": "Анна Петрова",
  "age": 25,
  "gender": "Женский"
}

### 2. СОЗДАТЬ ВТОРОГО ПОСЕТИТЕЛЯ (АНОНИМНО)
POST http://localhost:8080/api/visitors
Content-Type: application/json

{
  "age": 30,
  "gender": "Мужской"
}

### 3. СОЗДАТЬ РЕСТОРАН
POST http://localhost:8080/api/restaurants
Content-Type: application/json

{
  "name": "Pasta Paradise",
  "description": "Лучшая паста в городе",
  "cuisineType": "ITALIAN",
  "averageBill": 1200.00
}

### 4. ПОЛУЧИТЬ ВСЕХ ПОСЕТИТЕЛЕЙ
GET http://localhost:8080/api/visitors

### 5. ПОЛУЧИТЬ ВСЕ РЕСТОРАНЫ
GET http://localhost:8080/api/restaurants